# Generated by Django 4.1.3 on 2022-11-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0004_alter_haga_su_pedido_cantidad_de_personas'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('DNI', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='club_deportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('DNI', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='haga_su_pedido',
        ),
        migrations.DeleteModel(
            name='tipo_de_postre',
        ),
        migrations.DeleteModel(
            name='tipo_de_relleno',
        ),
    ]
